meta_product_name: "Josh Bolland | Full Stack Web Developer"
meta_title: "Josh Bolland | Full Stack Web Developer"
meta_description: "Josh Bolland | Full Stack Web Developer looking for exciting job opportunities"
meta_image: "josh.jpg"                       # should exist in `app/assets/images/`
